### ISSUE TITLE
I can contribute to adding Turkish language.

### ISSUE THREAD

**Issue by takomlii** [nasyx-rakeeb/weather-app-1#1]

**Comment by nasyx-rakeeb** [comment]
sure, I'd love that.

**Comment by takomlii** [comment]
Could you please email me the language file? emirhan@tr.edu.pl

**Comment by takomlii** [comment]
i have done most of the localization but i need your help for testing please contact me i will send you the source codes.

**Comment by nasyx-rakeeb** [comment]
sure, i will mail you on the above email address

**Comment by nasyx-rakeeb** [comment]
my email addres is: nasyxrakeeb2@gmail.com
Instagram: instagram.com/nasyx_rakeeb
twitter: twitter.com/nasyx-rakeeb

**Comment by takomlii** [comment]
Can u check mail?
